name: przewrotkapp_flutter
description: Potężna apka sprzętowa

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.1+1

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # Platform plugins
  url_launcher: ^6.3.2
  vibration: ^3.1.4
  clipboard: ^2.0.2
  flutter_native_splash: ^2.4.7
  image_picker: ^1.2.0

  # Logic
  go_router: ^16.3.0
  provider: ^6.1.5+1
  flutter_bloc: ^9.1.1
  rxdart: ^0.28.0
  collection: ^1.19.1
  flutter_image_compress: ^2.4.0

  # UI
  kalender: ^0.14.2
  calendar_date_picker2: ^2.0.1
  photo_view: ^0.15.0
  octo_image: ^2.1.0
  flutter_blurhash: ^0.9.1
  multi_image_picker_view: ^3.0.0
  intl: ^0.20.2

  # Serverpod
  serverpod_flutter: 2.9.2
  przewrotkapp_client:
    path: ../przewrotkapp_client
  serverpod_auth_shared_flutter: 2.9.2
  serverpod_auth_email_flutter: 2.9.2
  serverpod_auth_client: 2.9.2

dev_dependencies:
  flutter_lints: '>=3.0.0 <7.0.0'
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#ffffff"
  image: "assets/logo-black-transparent.png"
  web_image_mode: contain

flutter_launcher_icons:
  android: false
  ios: false
  web:
    generate: true
  image_path: "assets/logo-black-white-square.png"
  background_color: "#ffffff"
  theme_color: "#000000"
  icon_size: 64