name: przewrotkapp_flutter
description: A new Flutter project with Serverpod.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  go_router: ^16.2.1
  serverpod_flutter: 2.9.1
  przewrotkapp_client:
    path: ../przewrotkapp_client
  serverpod_auth_shared_flutter: 2.9.1
  serverpod_auth_email_flutter: 2.9.1
  provider: ^6.1.5+1
  rxdart: ^0.28.0
  collection: ^1.19.1
  intl: ^0.20.2
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4

  vibration: ^3.1.3
  clipboard: ^2.0.2

  kalender: ^0.13.0
  calendar_date_picker2: ^2.0.1
  photo_view: ^0.15.0

  serverpod_auth_client: any
dev_dependencies:
  flutter_lints: '>=3.0.0 <7.0.0'
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

flutter_launcher_icons:
  android: false
  ios: false
  web:
    generate: true
  image_path: "assets/logo-black-white-square.png"
  background_color: "#ffffff"
  theme_color: "#000000"
  icon_size: 64