# This is the configuration file for your local development environment. By
# default, it runs a single server on port 8080. To set up your server, you will
# need to add the name of the database you are connecting to and the user name.
# The password for the database is stored in the config/passwords.yaml.
#
# When running your server locally, the server ports are the same as the public
# facing ports.

# Configuration for the main API server.
apiServer:
  port: 8080
  publicHost: 0.0.0.0
  publicPort: 8080
  publicScheme: http

# Configuration for the web server.
webServer:
  port: 8082
  publicHost: 0.0.0.0
  publicPort: 8082
  publicScheme: http

# This is the database setup for your server.
database:
  host: localhost
  port: 5432
  name: przewrotkapp
  user: przewrotkapp
  #requireSsl: true # defaults to false
  #isUnixSocket: true # defaults to false

maxRequestSize: 5242880 # The maximum size of requests allowed in bytes

sessionLogs:
  consoleEnabled: true
  persistentEnabled: false
  consoleLogFormat: text # Defaults to "json", options are "text" or "json"

futureCallExecutionEnabled: true # Defaults to true
futureCall:
  concurrencyLimit: 2 # Defaults to 1, a negative or null value removes the limit
#  scanInterval: 5000 # Unit in milliseconds, defaults to 5000
