type: server

client_package_path: ../przewrotkapp_client
server_test_tools_path: test/integration/test_tools

modules:
  serverpod_auth:
    nickname: auth

experimental_features:
  inheritance: true
